### ISSUE TITLE
401 error - failing to set up component

### ISSUE THREAD

**Issue by grotteru** [Danielhiversen/home_assistant_min_renovasjon#14]
The Min renovasjon integration stopped working today. I get 401 errors in the log.

![image](https://github.com/Danielhiversen/home_assistant_min_renovasjon/assets/50191995/97c2dbe7-c285-4b94-8a61-0f68a191b1ca)

Here is a copy from the log:
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 22:16:10 (1 occurrences)
Last logged: 22:16:10

Error during setup of component min_renovasjon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/min_renovasjon/__init__.py", line 57, in setup
    min_renovasjon = MinRenovasjon(
                     ^^^^^^^^^^^^^^
  File "/config/custom_components/min_renovasjon/__init__.py", line 72, in __init__
    self._kalender_list = self._get_calendar_list()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/min_renovasjon/__init__.py", line 138, in _get_calendar_list
    kalender_list = self._parse_calendar_list(tommekalender, fraksjoner)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/min_renovasjon/__init__.py", line 154, in _parse_calendar_list
    tommekalender_json = json.loads(tommekalender)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Im not that familiar with HTTP-request responsens but doesnt 401 mean that there is something wrong with authentication?

**Comment by Kahera** [comment]
Same issue for me. Noticed the sensor didn't update after the last emptying two days ago, and when I restarted HA now I get errors setting it up: 

![image](https://github.com/Danielhiversen/home_assistant_min_renovasjon/assets/44864244/63a3a876-4613-44f8-8b2c-3ea18f86155c)

Logs show these two: 
![image](https://github.com/Danielhiversen/home_assistant_min_renovasjon/assets/44864244/88297d75-81c3-4ee7-87cd-673c2943409c)
![image](https://github.com/Danielhiversen/home_assistant_min_renovasjon/assets/44864244/f3970e3e-004e-4d0a-9cdf-759943dc3cb2)

I checked, and I also get a 401 when I try doing the call to get the same data through Postman. And I can see that my local renovation company does the call through a proxy when I use their website to check, but I get a 500 with the following text trying to call that `An application error occurred on the server. The current custom error settings for this
		application prevent the details of the application error from being viewed remotely (for security reasons). It
		could, however, be viewed by browsers running on the local server machine.`
![image](https://github.com/Danielhiversen/home_assistant_min_renovasjon/assets/44864244/82675043-9006-4e6c-b599-f8920d8c7814)

**Comment by ggranvik** [comment]
Has worked fine till today, 4 dec 2023. HA has been restarted several times the last days, without any problem with the integration until today.

**Comment by husjon** [comment]
I tested the app android app yesterday just to make sure and it works normally.

**Comment by jonberram** [comment]
> Yes, it is reverse-engineered of the solution from Norkart.
> 
> I expect they have changed something, but I have not yet had time to look into it. Have anyone tried their app to see if it works? https://play.google.com/store/apps/details?id=no.norkart.komtek.renovasjon.client&hl=no

If you used an old API key, this along with the old API has been disabled.

**Comment by tyldum** [comment]
If you hit norkart directly you get 409, if you go through their Azure endpoint it succeeds with that application ID:
`https://norkartrenovasjon.azurewebsites.net/proxyserver.ashx?server=https://komteksky.norkart.no/MinRenovasjon.Api/api/tommekalender/`

**Comment by TomTorger** [comment]
Got it to work. Two changes are required. As @tyldum mentioned, the end-point is accessed through the proxy, but in addition, you have to add "kommunenr" to the payload. Changes are as follows:

```
# Updated URLs
CONST_URL_FRAKSJONER = (
    "https://norkartrenovasjon.azurewebsites.net/proxyserver.ashx?server=https://komteksky.norkart.no/MinRenovasjon.Api/api/fraksjoner/"
)
CONST_URL_TOMMEKALENDER = (
    "https://norkartrenovasjon.azurewebsites.net/proxyserver.ashx?server=https://komteksky.norkart.no/MinRenovasjon.Api/api/tommekalender?"
    "kommunenr=[kommunenr]&gatenavn=[gatenavn]&gatekode=[gatekode]&husnr=[husnr]"
)

# And the request has to be updated
def _get_tommekalender_from_web_api(self):
    header = {
        CONST_KOMMUNE_NUMMER: self._kommunenr,
        CONST_APP_KEY: CONST_APP_KEY_VALUE,
    }

    url = CONST_URL_TOMMEKALENDER
    url = url.replace("[gatenavn]", self.gatenavn)
    url = url.replace("[gatekode]", self.gatekode)
    url = url.replace("[husnr]", self.husnr)
    url = url.replace("[kommunenr]", self._kommunenr) # Add kommunenr

    response = requests.get(url, headers=header)
    if response.status_code == requests.codes.ok:
        data = response.text
        return data
    else:
        _LOGGER.error(response.status_code)
        return None

**Comment by husjon** [comment]
I made a quick fork with the changes, I'm able to reach the API using curl, but I still get a 401 error in Home Assistant.
Gonna poke around a bit.

**Comment by husjon** [comment]
For some dumb reason the integration didn't update towards my fork, but after updating it manually in the `custom_integrations/` directory and restarting it worked.

@Danielhiversen I've created a PR for the changes. See: #15

**Comment by tyldum** [comment]
The new endpoint is not stable and has glaring security issues. The 500 errors are not caused by this addon and can't be fixed here.

**Comment by tortho** [comment]
anyone got any further on the 500 error?
¨¨¨
2023-12-31 00:03:31.945 INFO (SyncWorker_13) [custom_components.min_renovasjon] Refresh or no data. Fetching from API.
2023-12-31 00:03:32.247 ERROR (SyncWorker_13) [custom_components.min_renovasjon] 500
2023-12-31 00:03:32.680 DEBUG (SyncWorker_13) [custom_components.min_renovasjon] Tommekalender: None
2023-12-31 00:03:32.680 DEBUG (SyncWorker_13) [custom_components.min_renovasjon] Fraksjoner: [{"Id":1,"Navn":"Restavfall","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/restavfall.png","NorkartStandardFraksjonId":1,"NorkartStandardFraksjonIkon":"https://kttjeneste.norkart.no/Avfallssymboler/1.png"},{"Id":2,"Navn":"Papir/Papp","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/papir.png","NorkartStandardFraksjonId":6,"NorkartStandardFraksjonIkon":"https://kttjeneste.norkart.no/Avfallssymboler/6.png"},{"Id":3,"Navn":"Matavfall","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/matavfall.png","NorkartStandardFraksjonId":2,"NorkartStandardFraksjonIkon":"https://kttjeneste.norkart.no/Avfallssymboler/2.png"},{"Id":4,"Navn":"Glass/Metallemballasje","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/glassogmetallemballasje.png","NorkartStandardFraksjonId":5,"NorkartStandardFraksjonIkon":"https://kttjeneste.norkart.no/Avfallssymboler/5.png"},{"Id":5,"Navn":"Drikkekartonger","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":6,"Navn":"Spesialavfall","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":7,"Navn":"Plastemballasje","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/plastemballasje.png","NorkartStandardFraksjonId":4,"NorkartStandardFraksjonIkon":"https://kttjeneste.norkart.no/Avfallssymboler/4.png"},{"Id":8,"Navn":"Trevirke","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":9,"Navn":"Tekstiler","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":10,"Navn":"Hageavfall","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":11,"Navn":"Metaller","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":12,"Navn":"Hvitevarer/EE-avfall","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":13,"Navn":"Papp","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null},{"Id":14,"Navn":"M\u00F8bler","Ikon":"https://komteksky.norkart.no/MinRenovasjon.Api/Ikoner/brush.png","NorkartStandardFraksjonId":null,"NorkartStandardFraksjonIkon":null}]
¨¨¨

**Comment by husjon** [comment]
@tortho error 500 means an error with the server, usually it's a temporary issue.
I'd check the **Min Renovasjon** app just in case (see comment https://github.com/Danielhiversen/home_assistant_min_renovasjon/issues/14#issuecomment-1845520727).
