### ISSUE TITLE
Unable to set up component Min renovasjon

### ISSUE THREAD

**Issue by overas** [Danielhiversen/home_assistant_min_renovasjon#4]
I install the component "Min renovasjon" with HACS 1.18.0 and restarted HA. After restart I edited the example config and edited it with my street adresse, house_no and street_code. After HA restart I get error messages in the log about component "Error during setup of component min_renovasjon" and "Unable to prepare setup for platform min_renovasjon.sensor: Unable to set up component."

HACS install the component "Min renovasjon" in the path 
/root/config/custom_components/min_renovasjon

Using Hassos core-2021.12.0

Hassos log with log warning
2021-12-14 20:22:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration min_renovasjon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-14 20:22:23 ERROR (MainThread) [homeassistant.setup] Error during setup of component min_renovasjon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/min_renovasjon/__init__.py", line 57, in setup
    min_renovasjon = MinRenovasjon(
  File "/config/custom_components/min_renovasjon/__init__.py", line 72, in __init__
    self._kalender_list = self._get_calendar_list()
  File "/config/custom_components/min_renovasjon/__init__.py", line 138, in _get_calendar_list
    kalender_list = self._parse_calendar_list(tommekalender, fraksjoner)
  File "/config/custom_components/min_renovasjon/__init__.py", line 157, in _parse_calendar_list
    for calender_entry in tommekalender_json:
TypeError: 'bool' object is not iterable
2021-12-14 20:22:23 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform min_renovasjon.sensor: Unable to set up component.

**Comment by overas** [comment]
Min renovasjon fungerer nå. Feilmeldingen ovenfor er borte og jeg vet ikke helt hvorfor. Installerte Min renovasjon på nytt fra HACS og la inn i configuration.yaml:

`min_renovasjon:
  street_name: "Min gate"
  house_no: "32"
  street_code: "1866"
  county_id: "4202"
  date_format: "%d.%m.%Y" 

sensor:
  - platform: min_renovasjon
    fraction_id:
      - 1
      - 2
      - 3
      - 4
      - 7`

Bruker hassos core-2021.12.6 og Min renovasjon git ver. 91b3c61

![image](https://user-images.githubusercontent.com/37910044/147578791-6020be5c-0d30-4039-a35e-e694790a5ecf.png)

![image](https://user-images.githubusercontent.com/37910044/147579134-d80a92da-e3a1-47f9-998a-3d388518debc.png)

**Comment by overas** [comment]
Daniel, takk for at du holder Min renovasjon ved like.

**Comment by Amokk123** [comment]
Får følgende feilmelding ved installasjon av min_renovasjon.   

 result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/min_renovasjon/__init__.py", line 51, in setup
    street_name = config[DOMAIN][CONF_STREET_NAME]
KeyError: 'min_renovasjon'
2022-04-11 07:17:47 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform min_renovasjon.sensor: Unable to set up component.
