### ISSUE TITLE
Component not setting up after upgrade

### ISSUE THREAD

**Issue by Tjomsen** [Danielhiversen/home_assistant_min_renovasjon#6]
Hey! 
I just updated to Core 2022.5.5 and OS 8.0, and after restarting, I get the following errors/logs from min_renovasjon (same errors on subsequent restarts)
Any pointers on how to remedy, or is it a bug

![Snag_c5bbb0](https://user-images.githubusercontent.com/81190337/169535705-ac3ee788-0154-40b4-bc62-78fb847c5dc1.png)

![Snag_c5cd54](https://user-images.githubusercontent.com/81190337/169535724-6aba3e40-6e06-4368-b984-a486755b42b0.png)

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/min_renovasjon/__init__.py:97
Integration: Min renovasjon (documentation)
First occurred: 2:51:35 PM (1 occurrences)
Last logged: 2:51:35 PM

Error during setup of component min_renovasjon
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7b677d00>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='komteksky.norkart.no', port=443): Max retries exceeded with url: /komtek.renovasjonwebapi/api/tommekalender?gatenavn=Smebyvegen&gatekode=4035&husnr=130 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b677d00>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/min_renovasjon/__init__.py", line 57, in setup
    min_renovasjon = MinRenovasjon(
  File "/config/custom_components/min_renovasjon/__init__.py", line 72, in __init__
    self._kalender_list = self._get_calendar_list()
  File "/config/custom_components/min_renovasjon/__init__.py", line 134, in _get_calendar_list
    tommekalender, fraksjoner = self._get_from_web_api()
  File "/config/custom_components/min_renovasjon/__init__.py", line 121, in _get_from_web_api
    tommekalender = self._get_tommekalender_from_web_api()
  File "/config/custom_components/min_renovasjon/__init__.py", line 97, in _get_tommekalender_from_web_api
    response = requests.get(url, headers=header)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='komteksky.norkart.no', port=443): Max retries exceeded with url: /komtek.renovasjonwebapi/api/tommekalender?gatenavn=Smebyvegen&gatekode=4035&husnr=130 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b677d00>: Failed to establish a new connection: [Errno 110] Operation timed out'))

**Comment by nitefly80** [comment]
Hello,
I got the same errors

**Comment by Tjomsen** [comment]
It seems to be working with me today. May have been downtime of the api???

**Comment by Tjomsen** [comment]
still working, assuming intermittent downtime of some api or something, and closing
